services:
  php82:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php82
    shm_size: '1gb'
    tmpfs:
      - /tmp
    volumes:
      - type: bind
        source: ./
        target: /app
        bind:
          create_host_path: true
      - type: bind
        source: ./settings.ini
        target: /usr/local/etc/php/conf.d/settings.ini
    user: dev

  php82-xdebug:
    extends:
      service: php82
    build:
      target: php82-xdebug
    environment:
      PHP_IDE_CONFIG: "serverName=cli"
      XDEBUG_CONFIG: "client_host=${CLIENT_HOST:-172.20.0.1} start_with_request=trigger idekey=${IDEKEY:-PHPSTORM}"
      XDEBUG_MODE: "${XDEBUG_MODE:-develop,debug}"

  php82-pcov:
    extends:
      service: php82
    build:
      target: php82-pcov
