name: Code Quality
on: [push, pull_request]

jobs:
  phpcs:
    name: PHP ${{ matrix.php }} - PHP_CodeSniffer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PHP and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs

  phpstan:
    name: PHP ${{ matrix.php }} - PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PHP and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHPStan
        run: vendor/bin/phpstan --no-progress --no-ansi

  phpunit:
    name: PHP ${{ matrix.php }} - PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PHP and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHPUnit
        run: vendor/bin/phpunit --no-progress --coverage-text
